# Generated by Django 2.2.7 on 2019-11-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191108_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='exam_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
