# Generated by Django 2.2.7 on 2019-11-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
